---
AWSTemplateFormatVersion: "2010-09-09"
Description: Static website hosting with S3 and CloudFront

Resources:
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: staging.mytopsongs.site
      AccessControl: PublicRead
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  PublishUser:
    Type: AWS::IAM::User
    Properties:
      Policies:
        -
          PolicyName: !Sub publish-to-${S3Bucket}
          PolicyDocument:
            Statement:
              -
                Effect: Allow
                Action:
                  - s3:PutObject
                  - s3:GetObject
                  - s3:ListBucket
                  - s3:DeleteObject
                Resource:
                  - !Sub arn:aws:s3:::${S3Bucket}
                  - !Sub arn:aws:s3:::${S3Bucket}/*

  PublishCredentials:
    Type: AWS::IAM::AccessKey
    Properties:
      UserName: !Ref PublishUser

Outputs:
  AccessKeyId:
    Description: S3 Access Key
    Value: !Ref PublishCredentials

  AccessKeySecret:
    Description: S3 Secret Key
    Value: !GetAtt PublishCredentials.SecretAccessKey
